config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?

  root 'home#index'


  get 'home/index'
  devise_for :users, controllers: {
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  get 'users/dash_boards', to: 'users#dash_boards'

  resources :users do
    resources :articles
  end
  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  mount_uploader :img, ImgUploader
  validates :title, presence: true, length: { maximum: 10 }
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  has_many :articles, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller? 

  private

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys:[:name])
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :login_user

  def index
    @user = current_user
    @articles = @user.articles.all
  end

  def show
    @user = User.find(params[:user_id])
    @article = Article.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @article = Article.new
  end

  def create
    @user = User.find(params[:user_id])
    @article = @user.articles.new(article_params)
    if @article.save
      redirect_to user_article_path(@user, @article)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:user_id])
    @article = Article.find(params[:id])
  end

  def update
    @user = User.find(params[:user_id])
    @article = @user.articles.find(params[:id])
    if @article.update!(edit_article_params)
      redirect_to user_article_path(@user, @article)
    else
      render :edit
    end
  end

  def destroy
    @user = current_user
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to user_articles_path(@user)
  end

  private
    def article_params
      params.require(:user).permit(articles: [:title, :content, :img])[:articles]
    end

    def edit_article_params
      params.require(:article).permit(:title, :content, :img)
    end

    def login_user
      redirect_to new_user_session_path if current_user.nil?
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  def after_resetting_password_path_for(resource_name)
    users_dash_boards_path
  end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  def after_sign_up_path_for(resource)
    new_user_registration_path
  end

  def after_update_path_for(resource)
    users_dash_boards_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def after_sign_in_path_for(resource)
    users_dash_boards_path # ログイン後に遷移するpathを設定
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dash_boards
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <h1>記事の編集</h1>
      <div class="text-start">
        <%= form_with(model: @article, url: user_article_path, local: true) do |f| %>
          
            <%= f.label :title, class: "text-start" %>
            <%= f.text_field :title, class: "form-control" %>

            <%= f.label :content, class: "text-start" %>
            <%= f.text_area :content, class: "form-control" %>
            
            <%= f.label :img, class: "text-start" %>
            <%= f.file_field :img, class: "form-control" %>
          
          <div class="text-center">
            <%= f.submit "更新する", class: "btn btn-primary devise-btn" %>
          </div>
        <% end %>
        <p><%= link_to "戻る", user_articles_path(@user), class: "text-start" %></p>
      </div>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <h1>記事一覧</h1>
      <p><%= link_to "記事新規作成", new_user_article_path(@user), class: "btn btn-primary btn-block" %></p>
      <table class="table table-bordered table-condenced">
        <thead>
          <tr>
            <th>詳細表示</th>
            <th>タイトル</th>
            <th>内容</th>
            <th>画像</th>
            <th>編集・削除</th>
          </tr>
        </thead>
        <tbody>
          <% @articles.each do |article| %>
            <tr>
              <td><%= link_to "詳細", user_article_path(@user, article), class: "btn btn-primary" %></td>
              <td><%= article.title %></td>
              <td><%= article.content %></td>
              <td>
                <% if article.img.present? %>
                  <%= image_tag article.img.url, class: "article-img" %>
                <% end %>
              </td>
              <td class="article-buttons">
                <%= link_to "編集", edit_user_article_path(@user, article), class: "btn btn-success" %>
                <%= button_to "削除", user_article_path(@user, article), method: :delete, class: "btn btn-danger", data: { confirm: "本当に削除しますか？" } %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <h1>記事の新規作成</h1>
      <div class="text-start">
        <%= form_with(model: @user, url: user_articles_path, method: :post, local: true) do |f| %>
          <%= f.fields_for :articles do |article| %>
            <%= article.label :title, class: "text-start" %>
            <%= article.text_field :title, class: "form-control" %>

            <%= article.label :content, class: "text-start" %>
            <%= article.text_area :content, class: "form-control" %>
            
            <%= article.label :img, class: "text-start" %>
            <%= article.file_field :img, class: "form-control" %>
          <% end %>
          <div class="text-center">
            <%= f.submit "新規作成", class: "btn btn-primary" %>
          </div>
        <% end %>
        <p><%= link_to "戻る", user_articles_path(@user), class: "text-start" %></p>
      </div>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <h1>記事の詳細</h1>
      <table class="table table-bordered table-condenced">
        <thead>
          <tr>
            <th>タイトル</th>
            <th>内容</th>
            <th>画像</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= @article.title %></td>
            <td><%= @article.content %></td>
            <% if @article.img.present? %>
              <td><%= image_tag @article.img.url, class: "article-img" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
      <div class="article-buttons">
        <%= link_to "編集", edit_user_article_path(@user, @article), class: "btn btn-success devise-btn" %>
        <%= button_to "削除", user_article_path(@user, @article), method: :delete, class: "btn btn-danger devise-btn" %>
      </div>
        <%= link_to "記事一覧へ戻る", user_articles_path(@user), class: "btn btn-primary devise-btn" %>
    </div>
  </div>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<% if user_signed_in? %>
<%= current_user.name %>
<%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { "turbo-method": :delete }, class: "btn btn-primary" %>
<% else %>
<%= link_to "ログイン", new_user_session_path, class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PreJit1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/dash_boards.html.erb
<div class="container text-center">
  <div class="row">
    <div class="col-md-10 offset-md-1">
      <h1>Dash Boards</h1>
      <% if user_signed_in? %>
        <h2><%= current_user.name %></h2>
      <% end %>
      <%= link_to "記事一覧", user_articles_path(@user), class: "btn btn-primary devise-btn" %><br>
      <%= link_to t('devise.registrations.edit.edit'), edit_user_registration_path, class: "btn btn-primary devise-btn" %><br>
      <%= link_to t('devise.sessions.new.sign_out'), destroy_user_session_path, html: {method: :delete}, data: { "turbo-method": :delete }, class: "btn btn-warning devise-btn" %>
    </div>
  </div>
</div>